### ISSUE TITLE
Better representation of i24

### ISSUE THREAD

**Issue by vrtgs** [jmg049/i24#3]
does i24 have to/is wanted to be stored as a [u8;3]?

even assuming it is as #2 endianness is an issue

so currently there are 2 ways to go about representing this:
using a u32, with an always zero byte to allow for enum discriminant optimization, and faster loads and stores of the type
use the current layout but with native endianness

make from_i32 fallible

checked _ shouldn't have i32 overflow behavior, if it returns some then it was  valid operation, doing otherwise is confusing

**Comment by jmg049** [comment]
So I want to keep it as 3 bytes. I know there's alignment issues and what not but I don't want to lose the saving when storing to disk. Now this is probably easy to work around with the to_bytes functions since that is what will be used for saving and loading. Lots to consider and I hope to get around to it soon.

**Comment by vrtgs** [comment]
Alright, but I mean I don't see how in memory layout determines the size of the struct on disk

**Comment by jmg049** [comment]
Hence the last part of my comment about how it would actually be to_bytes ensuring the size on disk and after that we don't mind.

Sorry if I wasn't clear before, I tend to write comments in the form of thinking out loud.

**Comment by Vrtgs** [comment]
if only this was u24, then we would have had insanely fast division too😔

**Comment by jmg049** [comment]
Closed by [commit](https://github.com/jmg049/i24/commit/c81c0a02d2193abe3534affe2ac3c899fe638961)
